### ISSUE TITLE
Chart doesn't exists

### ISSUE THREAD

**Issue by AntonNazarenko** [bitfinexcom/bfx-hf-ui#48] opened 2019-11-06 14:26 UTC
![image](https://user-images.githubusercontent.com/51406639/68306145-a4a96e00-00b1-11ea-8220-b116ac14d41d.png)
After the first launch chart doesn't exist.

**Comment by f3rno** [comment] 2019-12-02 05:52
I cannot reproduce this, @AntonNazarenko can you confirm it is still a problem?

**Comment by AntonNazarenko** [comment] 2019-12-03 13:04
no, fixed it already

**Comment by f3rno** [comment] 2020-01-25 00:55
@JacobPlaster can you close this?

**Closed** 2020-01-28 12:19 UTC
Labels: bug
